### ISSUE TITLE
建议几点优化

### ISSUE THREAD

**Issue by jqqjj** [MaricoHan/redisson#40]
1. 续期看门狗不能及时退出，需要等到下一个ticker触发。锁请求量大时会消耗大量内存
2. 锁创建时就订阅了redis事件，如果只创建不用会造成资源浪费，应改到调用lock方法时再订阅
3. 创建的锁在unlock之后再重新调用lock方法时，没有订阅redis事件，造成的后果是无法快速感知别的线程释放锁。
4. 全文使用了不受控制的context.Context，无法方便摧毁释放资源

**Comment by troyhantech** [comment]
> 1. 续期看门狗不能及时退出，需要等到下一个ticker触发。锁请求量大时会消耗大量内存
> 2. 锁创建时就订阅了redis事件，如果只创建不用会造成资源浪费，应改到调用lock方法时再订阅
> 3. 创建的锁在unlock之后再重新调用lock方法时，没有订阅redis事件，造成的后果是无法快速感知别的线程释放锁。
> 4. 全文使用了不受控制的context.Context，无法方便摧毁释放资源

感谢建议！

**Comment by troyhantech** [comment]
> 1. 续期看门狗不能及时退出，需要等到下一个ticker触发。锁请求量大时会消耗大量内存
> 2. 锁创建时就订阅了redis事件，如果只创建不用会造成资源浪费，应改到调用lock方法时再订阅
> 3. 创建的锁在unlock之后再重新调用lock方法时，没有订阅redis事件，造成的后果是无法快速感知别的线程释放锁。
> 4. 全文使用了不受控制的context.Context，无法方便摧毁释放资源

1. #44 
2. #41  #47 
4. #47  
5. #42
